apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-svc
  labels:
    app: notification-svc
    name: notification-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-svc
  strategy: {}
  template:
    metadata:
      labels:
        app: notification-svc
    spec:
      containers:
        - image: shopnow/notification-svc:latest
          name: notification-svc
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: notification-svc
  labels:
    account: details
---
apiVersion: v1
kind: Service
metadata:
  name: notification-svc
spec:
  type: LoadBalancer
  selector:
    app: notification-svc
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080